exports.USER_NOT_FOUND = 404;
exports.INCOMPLETE_ACCOUNT = 301;
exports.INVALID_USER_CREDENTIAL = 401;
exports.INVALID_GRANT_TYPE = 400;
exports.INVALID_REFRESH_TOKEN = 400;
exports.INVALID_TOKEN = 400;

exports.INVALID_CLIENT = 401;
exports.INVALID_CLIENT_CREDENTIAL = 401;
exports.INVALID_CLIENT_GRANT_TYPE = 401;
exports.INVALID_CLIENT_REDIRECT_URI = 401;
exports.INVALID_CLIENT_SCOPE = 401;
exports.INVALID_CLIENT_REGISTRATION_CODE = 401;
exports.INVALID_CLIENT_REGISTRATION_CODE_EXPIRED = 401;
exports.CLIENT_REGISTRATION_FAILED = 401;